//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplicationTest1.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ftestEntities : DbContext
    {
        public ftestEntities()
            : base("name=ftestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<activitystream> activitystreams { get; set; }
        public DbSet<column> columns { get; set; }
        public DbSet<project> projects { get; set; }
        public DbSet<issue> issues { get; set; }
        public DbSet<sprint> sprints { get; set; }
        public DbSet<pojectdev> pojectdevs { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<attachment> attachments { get; set; }
    }
}
