//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplicationTest1.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class issue
    {
        public issue()
        {
            this.Tags1 = new HashSet<Tag>();
            this.attachments = new HashSet<attachment>();
            this.Comments = new HashSet<Comment>();
            this.activitystreams = new HashSet<activitystream>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Key Name is Required")]
        [StringLength(45, ErrorMessage = "Must be less than 45 letters")]
        public string keyname { get; set; }
        public int status { get; set; }
        [Required(ErrorMessage = "Description is Required")]
        public string descreption { get; set; }
           [Required(ErrorMessage = "Type is Required")]
        public string type { get; set; }
             [Required(ErrorMessage = "Priority is Required")]
        public string priority { get; set; }
        public string tags { get; set; }
        [RegularExpression("^[0-9]*$", ErrorMessage = "Estimate Must be numeric")]
        public Nullable<int> estimate { get; set; }
        public string assignee { get; set; }
        public Nullable<int> rankid { get; set; }
        public Nullable<int> sprintid { get; set; }
        public int projectid { get; set; }
    
        public virtual column column { get; set; }
        public virtual project project { get; set; }
        public virtual sprint sprint { get; set; }
        public virtual ICollection<Tag> Tags1 { get; set; }
        public virtual ICollection<attachment> attachments { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual issue issues1 { get; set; }
        public virtual issue issue1 { get; set; }
        public virtual ICollection<activitystream> activitystreams { get; set; }
    }
}
