//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplicationTest1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pojectdev
    {
        public int id { get; set; }
        public string devname { get; set; }
        public int projectid { get; set; }
    
        public virtual project project { get; set; }
    }
}
