//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplicationTest1.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class project
    {
        public project()
        {
            this.issues = new HashSet<issue>();
            this.columns = new HashSet<column>();
            this.sprints = new HashSet<sprint>();
            this.pojectdevs = new HashSet<pojectdev>();
            this.Tags = new HashSet<Tag>();
            this.attachments = new HashSet<attachment>();
            this.Comments = new HashSet<Comment>();
            this.activitystreams = new HashSet<activitystream>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Project Key is Required")]
        [StringLength(15, ErrorMessage = "Must be less than 15 letters")]
        public string projectkey { get; set; }
        public string date { get; set; }
        [Required(ErrorMessage = "Project Owner is Required")]
        public string projectowner { get; set; }

        public string projecttype { get; set; }
        public string projectleader { get; set; }
          [Required(ErrorMessage = "Project Name is Required")]
          [StringLength(40, ErrorMessage = "Must be less than 40 letters")]
        public string projectname { get; set; }
        public Nullable<int> currentsprint { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<issue> issues { get; set; }
        public virtual ICollection<column> columns { get; set; }
        public virtual sprint sprint { get; set; }
        public virtual ICollection<sprint> sprints { get; set; }
        public virtual ICollection<pojectdev> pojectdevs { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<attachment> attachments { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual project projects1 { get; set; }
        public virtual project project1 { get; set; }
        public virtual ICollection<activitystream> activitystreams { get; set; }
    }
}
