//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplicationTest1.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Tag
    {
        public int id { get; set; }
        public int issueid { get; set; }
        public int projectid { get; set; }
         [Required(ErrorMessage = "Tag Name is Required")]
         [StringLength(30, ErrorMessage = "Must be less than 30 letters")]
        public string Tag1 { get; set; }
    
        public virtual issue issue { get; set; }
        public virtual project project { get; set; }
    }
}
